### PR TITLE
Port commands from 'commander' to 'yargs'

### PR DESCRIPTION
**Pull request by avranju**
I am just raising this as an *exploratory* PR. I have ported all the commands from the existing `commander` NPM library to `yargs`. I think `yargs` allows us to structure the commands better. *But* this is a breaking change. There *maybe* a way of not breaking compat with older versions but it's likely to be somewhat hacky. Is doing a major version bump an option?

### CODE REVIEW

**Comment by avranju** [comment]
What this PR enables is basically experiences like the following. Say I want to look at the twin for a device. So I first run the following:
```
$ iothub-explorer
```
And get this:
```
[options] <command> [command-options] [command-args]

Commands:
  device <command>           Manage IoT Hub devices
  export-devices             Export devices in bulk from the device identity
                             registry. The list of devices gets exported to a
                             blob and then downloaded to a local file.
  import-devices             Import devices in bulk into the device identity
                             registry. The input file gets uploaded to a blob
                             and then an import job is started from that blob.
  job <command>              Manage IoT Hub jobs
  login <connection-string>  Create a temporary session on your IoT hub
  logout                     Terminate a temporary session on your IoT hub
  monitor <command>          Commands for monitoring various types of IoT Hub
                             events
  sas-token <device-id>      Generate a shared access signature token for the
                             given device with an expiry time <num-seconds> from
                             now

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```
`device` looks interesting. Let's see what's in it:
```
$ iothub-explorer device
```
And I get:
```
Commands:
  create <device-id|device-json>            Create a device identity in your IoT
                                            Hub device registry, either using
                                            the specified device id or JSON
                                            description.
  delete <device-id>                        Delete a device identity from your
                                            IoT hub device registry
  get <device-id>                           Get a device identity from your IoT
                                            hub device registry
  list                                      List the device identities currently
                                            in your IoT hub device registry
  method <device-id> <method-name>          Call a device method on a specific
  [method-payload] [method-timeout]         device
  send <device-id> <message>                Send a message to device
                                            (cloud-to-device/C2D).
  simulate [device-id]                      Simulate a device.
  twin <command>                            Manage IoT Hub device twins

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```
Hmm. There's a `twin` sub-command.
```
$ iothub-explorer device twin
```
And:
```
Commands:
  get <device-id>                   Get the twin of the specified device
  query <device-id>                 Query the registry for twins matching the
                                    SQL query passed as argument
  update <device-id> <device-json>  Update the twin of a device with the JSON
                                    description provided on the command line

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```
Ah. The `get` sub-command of the `twin` command looks like the thing I need.
```
$ iothub-explorer device twin get foo-device
```
And voila, I get what I was looking for!
```
deviceId:   foo-device          
etag:       AAAAAAAAAAw=      
properties:                   
  desired:                    
    modules:                  
      mongo-server:           
        name:    mongo-server 
        version: 1.0          
        type:    docker       

... more stuff here ....
```

**Comment by avranju** [comment]
Also, the source structure now looks like this instead of the current flat list of files:

image

**Review by damonbarry — COMMENTED** [review]
I think this looks really great. The current help output is ugly (although it was a big leap forward in terms of structure), so this is nice.

RE breaking changes, I'll defer to Pierre.

**Comment by pierreca** [comment]
While this PR is a great idea it'd require a major version bump because of the breaking changes it contains and we are not ready for that yet. Let's shelve it for now as we figure out what the future major version of iothub-explorer looks like.

**Pull request closed without merging**
